name: "Code Ready Dependency Analysis"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  analyze:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.13' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          crda: latest

      - name: CRDA Scan
        id: crda_scan
        uses: redhat-actions/crda@v1
        upload_sarif: true
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Report Link
        run: echo ${{ steps.crda_scan.outputs.report_link }}
